import type { Attributes } from '@fc27/data-sync';

export interface ChemistryStyle {
  /** EA's chemistry style id. */
  readonly id: number;
  readonly name: string;
  /** Goalkeeper styles apply only to goalkeepers, the others only to outfield players. */
  readonly goalkeeper: boolean;
  /** Attribute boosts at 3 chemistry. */
  readonly boosts: Partial<Readonly<Record<keyof Attributes, number>>>;
}

/** Every FC 27 chemistry style (source: FUT.GG, 2026-10-09; ADR-0006). */
export const CHEMISTRY_STYLES: readonly ChemistryStyle[] = [
  {
    id: 1,
    name: 'Basic',
    goalkeeper: false,
    boosts: {
      sprintSpeed: 3,
      positioning: 3,
      shotPower: 3,
      penalties: 3,
      vision: 3,
      shortPassing: 3,
      longPassing: 3,
      curve: 3,
      agility: 3,
      ballControl: 3,
      dribbling: 3,
      composure: 3,
      defensiveAwareness: 3,
      standingTackle: 3,
      slidingTackle: 3,
      strength: 3,
    },
  },
  {
    id: 2,
    name: 'Sniper',
    goalkeeper: false,
    boosts: {
      positioning: 9,
      finishing: 3,
      shotPower: 3,
      longShots: 6,
      volleys: 3,
      penalties: 3,
      stamina: 6,
      strength: 9,
      aggression: 3,
    },
  },
  {
    id: 3,
    name: 'Finisher',
    goalkeeper: false,
    boosts: {
      positioning: 6,
      finishing: 9,
      shotPower: 3,
      volleys: 3,
      penalties: 3,
      agility: 6,
      balance: 3,
      reactions: 3,
      dribbling: 9,
    },
  },
  {
    id: 4,
    name: 'Deadeye',
    goalkeeper: false,
    boosts: {
      positioning: 6,
      finishing: 3,
      shotPower: 9,
      longShots: 3,
      penalties: 3,
      vision: 3,
      shortPassing: 9,
      longPassing: 3,
      curve: 6,
    },
  },
  {
    id: 5,
    name: 'Marksman',
    goalkeeper: false,
    boosts: {
      finishing: 6,
      shotPower: 3,
      longShots: 6,
      penalties: 3,
      reactions: 6,
      ballControl: 6,
      dribbling: 3,
      composure: 3,
      jumping: 3,
      strength: 6,
    },
  },
  {
    id: 6,
    name: 'Hawk',
    goalkeeper: false,
    boosts: {
      acceleration: 3,
      sprintSpeed: 3,
      positioning: 3,
      finishing: 3,
      shotPower: 6,
      longShots: 6,
      penalties: 3,
      jumping: 6,
      strength: 3,
      aggression: 6,
    },
  },
  {
    id: 7,
    name: 'Artist',
    goalkeeper: false,
    boosts: {
      vision: 3,
      crossing: 6,
      shortPassing: 3,
      longPassing: 6,
      curve: 9,
      agility: 9,
      reactions: 6,
      dribbling: 3,
      composure: 3,
    },
  },
  {
    id: 8,
    name: 'Architect',
    goalkeeper: false,
    boosts: {
      vision: 6,
      freeKickAccuracy: 3,
      shortPassing: 9,
      longPassing: 3,
      curve: 6,
      stamina: 6,
      strength: 9,
      aggression: 3,
    },
  },
  {
    id: 9,
    name: 'Powerhouse',
    goalkeeper: false,
    boosts: {
      vision: 9,
      shortPassing: 6,
      longPassing: 6,
      curve: 3,
      interceptions: 6,
      defensiveAwareness: 3,
      standingTackle: 9,
      slidingTackle: 3,
    },
  },
  {
    id: 10,
    name: 'Maestro',
    goalkeeper: false,
    boosts: {
      positioning: 3,
      shotPower: 3,
      longShots: 6,
      vision: 3,
      freeKickAccuracy: 6,
      shortPassing: 3,
      longPassing: 6,
      reactions: 3,
      ballControl: 6,
      dribbling: 3,
      composure: 3,
    },
  },
  {
    id: 11,
    name: 'Engine',
    goalkeeper: false,
    boosts: {
      acceleration: 3,
      sprintSpeed: 3,
      vision: 3,
      crossing: 6,
      shortPassing: 3,
      longPassing: 3,
      curve: 6,
      agility: 3,
      balance: 6,
      dribbling: 6,
    },
  },
  {
    id: 12,
    name: 'Sentinel',
    goalkeeper: false,
    boosts: {
      interceptions: 6,
      headingAccuracy: 6,
      defensiveAwareness: 9,
      standingTackle: 3,
      slidingTackle: 3,
      jumping: 9,
      strength: 3,
      aggression: 6,
    },
  },
  {
    id: 13,
    name: 'Guardian',
    goalkeeper: false,
    boosts: {
      agility: 6,
      reactions: 3,
      ballControl: 3,
      dribbling: 6,
      composure: 3,
      interceptions: 3,
      defensiveAwareness: 6,
      standingTackle: 9,
      slidingTackle: 6,
    },
  },
  {
    id: 14,
    name: 'Gladiator',
    goalkeeper: false,
    boosts: {
      positioning: 3,
      shotPower: 6,
      longShots: 3,
      balance: 3,
      reactions: 6,
      ballControl: 3,
      dribbling: 3,
      interceptions: 3,
      headingAccuracy: 3,
      defensiveAwareness: 3,
      standingTackle: 3,
      slidingTackle: 6,
    },
  },
  {
    id: 15,
    name: 'Backbone',
    goalkeeper: false,
    boosts: {
      vision: 3,
      shortPassing: 3,
      longPassing: 6,
      interceptions: 6,
      defensiveAwareness: 3,
      standingTackle: 6,
      slidingTackle: 3,
      stamina: 6,
      strength: 3,
      aggression: 6,
    },
  },
  {
    id: 16,
    name: 'Anchor',
    goalkeeper: false,
    boosts: {
      acceleration: 3,
      sprintSpeed: 3,
      interceptions: 3,
      headingAccuracy: 3,
      defensiveAwareness: 3,
      standingTackle: 6,
      slidingTackle: 6,
      jumping: 6,
      strength: 6,
      aggression: 3,
    },
  },
  {
    id: 17,
    name: 'Hunter',
    goalkeeper: false,
    boosts: {
      acceleration: 6,
      sprintSpeed: 6,
      positioning: 3,
      finishing: 3,
      shotPower: 3,
      volleys: 9,
      penalties: 6,
    },
  },
  {
    id: 18,
    name: 'Catalyst',
    goalkeeper: false,
    boosts: {
      acceleration: 6,
      sprintSpeed: 6,
      vision: 9,
      crossing: 6,
      shortPassing: 3,
      longPassing: 6,
      curve: 3,
    },
  },
  {
    id: 19,
    name: 'Shadow',
    goalkeeper: false,
    boosts: {
      acceleration: 6,
      sprintSpeed: 6,
      interceptions: 3,
      headingAccuracy: 6,
      defensiveAwareness: 3,
      standingTackle: 3,
      slidingTackle: 9,
    },
  },
  {
    id: 20,
    name: 'GK Basic',
    goalkeeper: true,
    boosts: {
      acceleration: 3,
      gkDiving: 3,
      gkKicking: 3,
      gkHandling: 3,
      gkReflexes: 3,
      gkPositioning: 3,
    },
  },
  {
    id: 21,
    name: 'Wall',
    goalkeeper: true,
    boosts: { gkDiving: 9, gkHandling: 3, gkKicking: 6 },
  },
  {
    id: 22,
    name: 'Glove',
    goalkeeper: true,
    boosts: { gkDiving: 6, gkHandling: 9, gkPositioning: 3 },
  },
  {
    id: 23,
    name: 'Shield',
    goalkeeper: true,
    boosts: { gkKicking: 6, gkReflexes: 9, sprintSpeed: 3 },
  },
  {
    id: 24,
    name: 'Cat',
    goalkeeper: true,
    boosts: { acceleration: 3, gkPositioning: 9, gkReflexes: 6 },
  },
];
