import type { Position } from '@fc27/data-sync';

/** A position slot of a formation, e.g. `RCB`, whose card position is `CB`. */
export interface FormationSlot {
  readonly code: string;
  readonly position: Position;
}

export interface Formation {
  /** EA's formation id, as used by FUT.GG. */
  readonly id: number;
  readonly name: string;
  /** The eleven starting slots, goalkeeper first. */
  readonly slots: readonly FormationSlot[];
}

const slot = (code: string, position: Position): FormationSlot => ({ code, position });

/** Every FC 27 Ultimate Team formation (source: FUT.GG, 2026-10-09; ADR-0006). */
export const FORMATIONS: readonly Formation[] = [
  {
    id: 22,
    name: '3-1-4-2',
    slots: [
      slot('GK', 'GK'),
      slot('RCB', 'CB'),
      slot('CB', 'CB'),
      slot('LCB', 'CB'),
      slot('CDM', 'CDM'),
      slot('RM', 'RM'),
      slot('RCM', 'CM'),
      slot('LCM', 'CM'),
      slot('LM', 'LM'),
      slot('RS', 'ST'),
      slot('LS', 'ST'),
    ],
  },
  {
    id: 23,
    name: '3-4-1-2',
    slots: [
      slot('GK', 'GK'),
      slot('RCB', 'CB'),
      slot('CB', 'CB'),
      slot('LCB', 'CB'),
      slot('RM', 'RM'),
      slot('RCM', 'CM'),
      slot('LCM', 'CM'),
      slot('LM', 'LM'),
      slot('CAM', 'CAM'),
      slot('RS', 'ST'),
      slot('LS', 'ST'),
    ],
  },
  {
    id: 24,
    name: '3-4-2-1',
    slots: [
      slot('GK', 'GK'),
      slot('RCB', 'CB'),
      slot('CB', 'CB'),
      slot('LCB', 'CB'),
      slot('RM', 'RM'),
      slot('RCM', 'CM'),
      slot('LCM', 'CM'),
      slot('LM', 'LM'),
      slot('RAM', 'CAM'),
      slot('LAM', 'CAM'),
      slot('ST', 'ST'),
    ],
  },
  {
    id: 25,
    name: '3-4-3',
    slots: [
      slot('GK', 'GK'),
      slot('RCB', 'CB'),
      slot('CB', 'CB'),
      slot('LCB', 'CB'),
      slot('RM', 'RM'),
      slot('RCM', 'CM'),
      slot('LCM', 'CM'),
      slot('LM', 'LM'),
      slot('RW', 'RW'),
      slot('ST', 'ST'),
      slot('LW', 'LW'),
    ],
  },
  {
    id: 27,
    name: '3-5-2',
    slots: [
      slot('GK', 'GK'),
      slot('RCB', 'CB'),
      slot('CB', 'CB'),
      slot('LCB', 'CB'),
      slot('RDM', 'CDM'),
      slot('LDM', 'CDM'),
      slot('RM', 'RM'),
      slot('LM', 'LM'),
      slot('CAM', 'CAM'),
      slot('RS', 'ST'),
      slot('LS', 'ST'),
    ],
  },
  {
    id: 14,
    name: '4-1-2-1-2 Wide',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('CDM', 'CDM'),
      slot('RM', 'RM'),
      slot('LM', 'LM'),
      slot('CAM', 'CAM'),
      slot('RS', 'ST'),
      slot('LS', 'ST'),
    ],
  },
  {
    id: 15,
    name: '4-1-2-1-2 Narrow',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('CDM', 'CDM'),
      slot('RCM', 'CM'),
      slot('LCM', 'CM'),
      slot('CAM', 'CAM'),
      slot('RS', 'ST'),
      slot('LS', 'ST'),
    ],
  },
  {
    id: 1,
    name: '4-1-3-2',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('CDM', 'CDM'),
      slot('RM', 'RM'),
      slot('CM', 'CM'),
      slot('LM', 'LM'),
      slot('RS', 'ST'),
      slot('LS', 'ST'),
    ],
  },
  {
    id: 2,
    name: '4-1-4-1',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('CDM', 'CDM'),
      slot('RM', 'RM'),
      slot('RCM', 'CM'),
      slot('LCM', 'CM'),
      slot('LM', 'LM'),
      slot('ST', 'ST'),
    ],
  },
  {
    id: 36,
    name: '4-2-1-3',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('RDM', 'CDM'),
      slot('LDM', 'CDM'),
      slot('CAM', 'CAM'),
      slot('RW', 'RW'),
      slot('ST', 'ST'),
      slot('LW', 'LW'),
    ],
  },
  {
    id: 13,
    name: '4-2-2-2',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('RDM', 'CDM'),
      slot('LDM', 'CDM'),
      slot('RAM', 'CAM'),
      slot('LAM', 'CAM'),
      slot('RS', 'ST'),
      slot('LS', 'ST'),
    ],
  },
  {
    id: 3,
    name: '4-2-3-1',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('RDM', 'CDM'),
      slot('LDM', 'CDM'),
      slot('RAM', 'CAM'),
      slot('CAM', 'CAM'),
      slot('LAM', 'CAM'),
      slot('ST', 'ST'),
    ],
  },
  {
    id: 4,
    name: '4-2-3-1 Wide',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('RDM', 'CDM'),
      slot('LDM', 'CDM'),
      slot('RM', 'RM'),
      slot('LM', 'LM'),
      slot('CAM', 'CAM'),
      slot('ST', 'ST'),
    ],
  },
  {
    id: 5,
    name: '4-2-4',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('RCM', 'CM'),
      slot('LCM', 'CM'),
      slot('RW', 'RW'),
      slot('RS', 'ST'),
      slot('LS', 'ST'),
      slot('LW', 'LW'),
    ],
  },
  {
    id: 6,
    name: '4-3-1-2',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('RCM', 'CM'),
      slot('CM', 'CM'),
      slot('LCM', 'CM'),
      slot('CAM', 'CAM'),
      slot('RS', 'ST'),
      slot('LS', 'ST'),
    ],
  },
  {
    id: 7,
    name: '4-3-2-1',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('RCM', 'CM'),
      slot('CM', 'CM'),
      slot('LCM', 'CM'),
      slot('RAM', 'CAM'),
      slot('LAM', 'CAM'),
      slot('ST', 'ST'),
    ],
  },
  {
    id: 8,
    name: '4-3-3',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('RCM', 'CM'),
      slot('CM', 'CM'),
      slot('LCM', 'CM'),
      slot('RW', 'RW'),
      slot('ST', 'ST'),
      slot('LW', 'LW'),
    ],
  },
  {
    id: 9,
    name: '4-3-3 Holding',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('CDM', 'CDM'),
      slot('RCM', 'CM'),
      slot('LCM', 'CM'),
      slot('RW', 'RW'),
      slot('ST', 'ST'),
      slot('LW', 'LW'),
    ],
  },
  {
    id: 10,
    name: '4-3-3 Defend',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('RDM', 'CDM'),
      slot('LDM', 'CDM'),
      slot('CM', 'CM'),
      slot('RW', 'RW'),
      slot('ST', 'ST'),
      slot('LW', 'LW'),
    ],
  },
  {
    id: 11,
    name: '4-3-3 Attack',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('RCM', 'CM'),
      slot('LCM', 'CM'),
      slot('CAM', 'CAM'),
      slot('RW', 'RW'),
      slot('ST', 'ST'),
      slot('LW', 'LW'),
    ],
  },
  {
    id: 18,
    name: '4-4-1-1',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('RM', 'RM'),
      slot('RCM', 'CM'),
      slot('LCM', 'CM'),
      slot('LM', 'LM'),
      slot('CAM', 'CAM'),
      slot('ST', 'ST'),
    ],
  },
  {
    id: 16,
    name: '4-4-2',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('RM', 'RM'),
      slot('RCM', 'CM'),
      slot('LCM', 'CM'),
      slot('LM', 'LM'),
      slot('RS', 'ST'),
      slot('LS', 'ST'),
    ],
  },
  {
    id: 17,
    name: '4-4-2 Holding',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('RDM', 'CDM'),
      slot('LDM', 'CDM'),
      slot('RM', 'RM'),
      slot('LM', 'LM'),
      slot('RS', 'ST'),
      slot('LS', 'ST'),
    ],
  },
  {
    id: 21,
    name: '4-5-1 Attack',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('RM', 'RM'),
      slot('CM', 'CM'),
      slot('LM', 'LM'),
      slot('RAM', 'CAM'),
      slot('LAM', 'CAM'),
      slot('ST', 'ST'),
    ],
  },
  {
    id: 20,
    name: '4-5-1 Flat',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('RM', 'RM'),
      slot('RCM', 'CM'),
      slot('CM', 'CM'),
      slot('LCM', 'CM'),
      slot('LM', 'LM'),
      slot('ST', 'ST'),
    ],
  },
  {
    id: 29,
    name: '5-2-1-2',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('CB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('RCM', 'CM'),
      slot('LCM', 'CM'),
      slot('CAM', 'CAM'),
      slot('RS', 'ST'),
      slot('LS', 'ST'),
    ],
  },
  {
    id: 30,
    name: '5-2-3',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('CB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('RCM', 'CM'),
      slot('LCM', 'CM'),
      slot('RW', 'RW'),
      slot('ST', 'ST'),
      slot('LW', 'LW'),
    ],
  },
  {
    id: 31,
    name: '5-3-2',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('CB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('CDM', 'CDM'),
      slot('RCM', 'CM'),
      slot('LCM', 'CM'),
      slot('RS', 'ST'),
      slot('LS', 'ST'),
    ],
  },
  {
    id: 33,
    name: '5-4-1',
    slots: [
      slot('GK', 'GK'),
      slot('RB', 'RB'),
      slot('RCB', 'CB'),
      slot('CB', 'CB'),
      slot('LCB', 'CB'),
      slot('LB', 'LB'),
      slot('RM', 'RM'),
      slot('RCM', 'CM'),
      slot('LCM', 'CM'),
      slot('LM', 'LM'),
      slot('ST', 'ST'),
    ],
  },
];
