import { POSITION_GROUPS, ratingFromTerms } from '@fc27/domain';
import type { PositionGroup, TrueRatingRules } from '@fc27/domain';

import { meanAbsoluteError, spearman } from './metrics.js';
import type { CalibrationRow } from './rows.js';

/** Acceptance bounds per group on the held-out cards (design §4). */
export const MAX_MEAN_ABSOLUTE_ERROR = 1.5;
export const MIN_SPEARMAN = 0.9;

export interface GroupAccuracy {
  readonly group: PositionGroup;
  readonly cards: number;
  readonly rows: number;
  readonly meanAbsoluteError: number;
  readonly spearman: number;
  readonly passes: boolean;
}

export interface Disagreement {
  readonly row: CalibrationRow;
  readonly rating: number;
}

export function rate(row: CalibrationRow, rules: TrueRatingRules): number {
  return ratingFromTerms(row.terms, rules.groups[row.group], rules);
}

/** Accuracy of the rules on the rows, per group, in `POSITION_GROUPS` order. */
export function accuracy(rows: readonly CalibrationRow[], rules: TrueRatingRules): GroupAccuracy[] {
  return POSITION_GROUPS.map((group) => {
    const members = rows.filter((row) => row.group === group);
    const ratings = members.map((row) => rate(row, rules));
    const references = members.map((row) => row.reference);
    const error = meanAbsoluteError(ratings, references);
    const correlation = spearman(ratings, references);
    return {
      group,
      cards: new Set(members.map((row) => row.eaId)).size,
      rows: members.length,
      meanAbsoluteError: error,
      spearman: correlation,
      passes: members.length > 0 && error <= MAX_MEAN_ABSOLUTE_ERROR && correlation >= MIN_SPEARMAN,
    };
  });
}

/** The rows the rules rate furthest from the reference, largest gap first. */
export function largestDisagreements(
  rows: readonly CalibrationRow[],
  rules: TrueRatingRules,
  count: number,
): Disagreement[] {
  return rows
    .map((row) => ({ row, rating: rate(row, rules) }))
    .sort(
      (a, b) =>
        Math.abs(b.rating - b.row.reference) - Math.abs(a.rating - a.row.reference) ||
        a.row.eaId - b.row.eaId,
    )
    .slice(0, count);
}

export interface ReportInput {
  readonly date: string;
  readonly sampledCards: number;
  readonly trainingCards: number;
  readonly heldOutCards: number;
  readonly rules: TrueRatingRules;
  readonly heldOut: readonly GroupAccuracy[];
  readonly disagreements: readonly Disagreement[];
}

const fixed = (value: number, digits: number) => value.toFixed(digits);

/** The calibration report committed as docs/domain/true-rating-calibration.md. */
export function calibrationReport(input: ReportInput): string {
  const failing = input.heldOut.filter((group) => !group.passes).map((group) => group.group);
  return [
    '# True-rating calibration',
    '',
    'Generated by `@fc27/calibration` (design: [true-rating.md](true-rating.md) §4). Re-run the',
    '**True-rating calibration** workflow to refresh it after a game update.',
    '',
    `- **Date:** ${input.date}`,
    `- **Sample:** ${input.sampledCards} cards with meta ratings; ${input.trainingCards} for fitting, ${input.heldOutCards} held out`,
    `- **PlayStyle+ multiplier (β):** ${input.rules.playStylePlusMultiplier}`,
    `- **Acceptance:** mean absolute error ≤ ${MAX_MEAN_ABSOLUTE_ERROR} and Spearman ≥ ${MIN_SPEARMAN} per group on the held-out cards`,
    `- **Result:** ${failing.length === 0 ? 'every group passes' : `${failing.join(', ')} miss the bounds`}`,
    '',
    '## Accuracy on the held-out cards',
    '',
    '| Group | Cards | Rows | Mean absolute error | Spearman | Passes |',
    '| ----- | ----: | ---: | ------------------: | -------: | ------ |',
    ...input.heldOut.map(
      (group) =>
        `| ${group.group} | ${group.cards} | ${group.rows} | ${fixed(group.meanAbsoluteError, 2)} | ${fixed(group.spearman, 3)} | ${group.passes ? 'Yes' : 'No'} |`,
    ),
    '',
    '## Largest disagreements on the held-out cards',
    '',
    '| Card | Position | Chemistry style | True rating | Reference |',
    '| ---- | -------- | --------------- | ----------: | --------: |',
    ...input.disagreements.map(
      ({ row, rating }) =>
        `| ${row.name} (${row.eaId}) | ${row.position} | ${row.style} | ${fixed(rating, 1)} | ${fixed(row.reference, 1)} |`,
    ),
    '',
  ].join('\n');
}
