import { describe, expect, it } from 'vitest';

import { TRUE_RATING_RULES } from '@fc27/domain';
import type { GroupWeights, TrueRatingRules, TrueRatingTerms } from '@fc27/domain';
import { accuracy, calibrationReport, largestDisagreements, rate } from './report.js';
import type { CalibrationRow } from './rows.js';

const terms = (finishing: number): TrueRatingTerms =>
  ({
    attributes: { finishing },
    weakFoot: 0,
    skillMoves: 0,
    accelerate: 0,
    height: 0,
    playStyles: 0,
    playStylesPlus: 0,
    role: 0,
  }) as unknown as TrueRatingTerms;

const FINISHING: GroupWeights = {
  attributes: { finishing: 1 },
  weakFoot: 0,
  skillMoves: 0,
  accelerate: 0,
  height: 0,
  playStyles: 0,
};
const RULES: TrueRatingRules = {
  ...TRUE_RATING_RULES,
  groups: { ...TRUE_RATING_RULES.groups, ST: FINISHING, CB: FINISHING },
};

const row = (eaId: number, finishing: number, reference: number, group: 'ST' | 'CB' = 'ST') =>
  ({
    eaId,
    name: `Card ${eaId}`,
    position: group,
    group,
    style: 'Basic',
    terms: terms(finishing),
    reference,
  }) satisfies CalibrationRow;

describe('rate', () => {
  it('rates a row with its group’s weights', () => {
    expect(rate(row(1, 81.25, 0), RULES)).toBe(81.3);
  });
});

describe('accuracy', () => {
  it('measures each group against the acceptance bounds', () => {
    // ST: ratings 80, 85, 90 against 81, 86, 90: error 2/3 ≈ 0.67, same order: passes.
    // CB: ratings 70, 75 against 77, 71: error (7 + 4)/2 = 5.5, reversed order: fails.
    const result = accuracy(
      [row(1, 80, 81), row(1, 85, 86), row(2, 90, 90), row(3, 70, 77, 'CB'), row(4, 75, 71, 'CB')],
      RULES,
    );
    expect(result.map((group) => group.group)).toEqual([
      'GK',
      'CB',
      'FB',
      'CDM',
      'CM',
      'CAM',
      'WM',
      'W',
      'ST',
    ]);
    expect(result[8]).toEqual({
      group: 'ST',
      cards: 2,
      rows: 3,
      meanAbsoluteError: 2 / 3,
      spearman: 1,
      passes: true,
    });
    expect(result[1]).toMatchObject({
      cards: 2,
      meanAbsoluteError: 5.5,
      spearman: -1,
      passes: false,
    });
    expect(result[0]).toEqual({
      group: 'GK',
      cards: 0,
      rows: 0,
      meanAbsoluteError: 0,
      spearman: 0,
      passes: false,
    });
  });

  it('passes exactly at the bounds', () => {
    // Errors 1.5 each way: ratings 80 and 90 against 81.5 and 88.5, same order.
    expect(accuracy([row(1, 80, 81.5), row(2, 90, 88.5)], RULES)[8]?.passes).toBe(true);
    expect(accuracy([row(1, 80, 81.6), row(2, 90, 88.5)], RULES)[8]?.passes).toBe(false);
  });
});

describe('largestDisagreements', () => {
  it('lists the rows furthest from their reference, ties by EA id', () => {
    const rows = [row(3, 80, 82), row(1, 80, 75), row(2, 80, 78), row(4, 80, 80)];
    expect(largestDisagreements(rows, RULES, 3)).toEqual([
      { row: rows[1], rating: 80 },
      { row: rows[2], rating: 80 },
      { row: rows[0], rating: 80 },
    ]);
  });
});

describe('calibrationReport', () => {
  it('reports the sample, β, the accuracy per group and the largest disagreements', () => {
    const st = {
      group: 'ST' as const,
      cards: 2,
      rows: 3,
      meanAbsoluteError: 2 / 3,
      spearman: 1,
      passes: true,
    };
    const cb = {
      group: 'CB' as const,
      cards: 2,
      rows: 2,
      meanAbsoluteError: 5.5,
      spearman: -1,
      passes: false,
    };
    const report = calibrationReport({
      date: '2026-10-09',
      sampledCards: 700,
      trainingCards: 560,
      heldOutCards: 140,
      rules: { ...RULES, playStylePlusMultiplier: 2.5 },
      heldOut: [cb, st],
      disagreements: [{ row: row(4, 75, 71, 'CB'), rating: 75 }],
    });
    expect(report.split('\n')).toEqual([
      '# True-rating calibration',
      '',
      'Generated by `@fc27/calibration` (design: [true-rating.md](true-rating.md) §4). Re-run the',
      '**True-rating calibration** workflow to refresh it after a game update.',
      '',
      '- **Date:** 2026-10-09',
      '- **Sample:** 700 cards with meta ratings; 560 for fitting, 140 held out',
      '- **PlayStyle+ multiplier (β):** 2.5',
      '- **Acceptance:** mean absolute error ≤ 1.5 and Spearman ≥ 0.9 per group on the held-out cards',
      '- **Result:** CB miss the bounds',
      '',
      '## Accuracy on the held-out cards',
      '',
      '| Group | Cards | Rows | Mean absolute error | Spearman | Passes |',
      '| ----- | ----: | ---: | ------------------: | -------: | ------ |',
      '| CB | 2 | 2 | 5.50 | -1.000 | No |',
      '| ST | 2 | 3 | 0.67 | 1.000 | Yes |',
      '',
      '## Largest disagreements on the held-out cards',
      '',
      '| Card | Position | Chemistry style | True rating | Reference |',
      '| ---- | -------- | --------------- | ----------: | --------: |',
      '| Card 4 (4) | CB | Basic | 75.0 | 71.0 |',
      '',
    ]);
  });

  it('says so when every group passes', () => {
    const report = calibrationReport({
      date: '2026-10-09',
      sampledCards: 1,
      trainingCards: 1,
      heldOutCards: 0,
      rules: RULES,
      heldOut: [],
      disagreements: [],
    });
    expect(report).toContain('- **Result:** every group passes');
  });
});
